version: "3.9"
services:
  postgres:
    image: postgres
    container_name: gaave-postgres
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=api
      - POSTGRES_DB=gaave
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
